modLoader="javafml"
loaderVersion="[35,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
[[mods]]
    modId="aerobaticelytra"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    itemIcon="aerobaticelytra:aerobatic_elytra"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[modproperties.aerobaticelytra]
    catalogueImageIcon="aerobaticelytra.png"
[[dependencies.aerobaticelytra]]
    modId="flightcore"
    mandatory=true
    versionRange="[1.0,2.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="simpleconfig"
    versionRange="[1.0,2.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="lazulib"
    versionRange="[1.0,2.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="caelus"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="curios"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"