modLoader="javafml"
loaderVersion="[35,)"
license="${license}"
#issueTrackerURL="${issue_tracker}"
[[mods]]
	modId="aerobaticelytra"
	version="${version}"
	displayName="${display}"
	#updateJSONURL="${update_json}"
	#displayURL="${page}"
	logoFile="${logo_file}"
    itemIcon="aerobaticelytra:aerobatic_elytra"
	credits="${credits}"
	authors="${authors}"
	description='''${description}'''
[[dependencies.aerobaticelytra]]
    modId="flightcore"
    mandatory=true
    versionRange="[0.5,1.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="simpleconfig"
    versionRange="[1.0,2.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="endorutil"
    versionRange="[0.5,1.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="caelus"
    mandatory=false
    versionRange="[1.18.1-3.0,1.18.1-4.0)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.aerobaticelytra]]
    modId="elytra-shot"
    mandatory=false
    versionRange="[1.18.2-5.0,1.18.2-6.0)"
    ordering="AFTER"
    side="BOTH"